import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './styles/globals.scss'
import React, {PropsWithChildren} from "react";
import Header from "@/components/Header/Header";

const montserrat  = Montserrat({ subsets: ['latin'],weight:['400','600','700','500'] })

export const metadata: Metadata = {
  title: 'Alai Destinations',
  description: 'Generated by create next app',
}

const  RootLayout: React.FC<PropsWithChildren> = ({children})=> {
  return (
    <html lang="en">
      <body className={montserrat.className}>
      <Header />
      <main>
          {children}
      </main>

      </body>
    </html>
  )
}

export default RootLayout;
