import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.scss'
import React, {PropsWithChildren} from "react";
import { register } from 'swiper/element/bundle';


const montserrat  = Montserrat({ subsets: ['latin'],weight:['400','600','700','500'] })

export const metadata: Metadata = {
  title: 'Alai Destinations',
  description: 'Generated by create next app',
}
// register Swiper custom elements
register();

const  RootLayout: React.FC<PropsWithChildren> = ({children})=> {
  return (
    <html lang="en">
      <body className={montserrat.className}>
      <header></header>
      <main>
          {children}
      </main>

      </body>
    </html>
  )
}

export default RootLayout;
