import { Html, Head, Main, NextScript } from 'next/document';
import { Metadata } from 'next';
import { montserrat } from '../../fontConfig';
import Script from 'next/script';

export const metadata: Metadata = {
  title: 'Alai Destinations',
  description: 'Generated by create next app',
};

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <Script src={'//code.jivosite.com/widget/R7jumzTf9R'} strategy="beforeInteractive" />
      </Head>
      <body className={montserrat.className}>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
